# Site
name: SEON
description: Little stories of romantic dreams.
meta_description: "Little stories of romantic dreams."
logo: 'assets/images/seon-logo.png'
favicon: 'assets/images/logo.png'
paginate: 15
baseurl:
google_analytics: 'UA-118575550-1'
disqus: 'blog.seonology.com'

# Authors
authors:
  seon:
    name: Seon Noh
    display_name: SEON
    gravatar: b75be5ca1ce79b730f75030cec42ea81
    email: dark.pearl.nst@gmail.com
    web: https://blog.seonology.com
    description: "일본에서 살고 있는 흔한 한국인 개발자입니다. <br> 현재는 NC Japan에서 일하고 있으며, 한적한 치바 시골마을에서 로멘틱한 일상을 꿈꾸며 살아가고 있습니다."
    facebook: https://www.facebook.com/seon.noh.79

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge